version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.0.2

executors:
  web-executor:
    docker:
      - image: cimg/node:16.3.0
  docker-executor:
    docker:
      - image: cimg/base:2021.02

parameters:
  build-web:
    type: boolean
    default: false

workflows:
  version: 2

  build-web:
    when: << pipeline.parameters.build-web >>
    jobs:
      - build-web

commands:
  cached-checkout:
    description: "Checkout with caching"
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - run:
          name: git config merge.renameLimit
          command: git config merge.renameLimit 999999
      - run:
          name: git fetch origin
          command: git fetch origin
      - save_cache:
          key: source-v100-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  restore-nodejs-cache:
    description: "NodeJS: Calculate cache key and restore cache"
    steps:
      - run:
          name: Calculate cache key
          command: find web -name package\*.json | grep -v /target/ | sort -u | xargs cat > nodejs-dependency-json-cache.key
      - restore_cache:
          keys:
            - web-nodejs-dependencies-v100-{{ checksum "nodejs-dependency-json-cache.key" }}
  save-nodejs-cache:
    description: "NodeJS: Save cache"
    steps:
      - save_cache:
          key: web-nodejs-dependencies-v100-{{ checksum "nodejs-dependency-json-cache.key" }}
          paths:
            - web/navbar/node_modules
            - web/nodes/node_modules
            - web/root-config/node_modules
  build-micro-frontend-app:
    description: "Build one of the micro-frontend apps"
    parameters:
      app:
        description: name of the app to build
        type: string
    steps:
      - run:
          name: Install dependencies (<< parameters.app >>)
          command: |
            cd web/<< parameters.app >>
            npm install
      - run:
          name: Build (<< parameters.app >>)
          command: |
            cd web/<< parameters.app >>
            npm run-script build

jobs:
  build-web:
    executor: web-executor
    steps:
      - checkout
      - restore-nodejs-cache
      - save-nodejs-cache
      - build-micro-frontend-app:
          app: root-config
      - build-micro-frontend-app:
          app: nodes
      - build-micro-frontend-app:
          app: navbar
      - persist_to_workspace:
          root: ~/project
          paths: web
