version: 2.1

orbs:
  path-filtering: circleci/path-filtering@0.0.2

executors:
  web-executor:
    docker:
      - image: cimg/node:16.3.0
  docker-executor:
    docker:
      - image: docker:20.10.1-git
  centos-build-executor:
    docker:
      - image: opennms/build-env:11.0.9.11-3.6.3-b5958

parameters:
  build-web:
    type: boolean
    default: false

workflows:
  version: 2

  build-web:
    when: << pipeline.parameters.build-web >>
    jobs:
      - build-web
      - build-container:
          requires:
            - build-web
      - deploy-container:
          requires:
            - build-container

commands:
  restore-nodejs-cache:
    description: "NodeJS: Calculate cache key and restore cache"
    steps:
      - run:
          name: Calculate cache key
          command: find web -name package\*.json | grep -v /target/ | sort -u | xargs cat > nodejs-dependency-json-cache.key
      - restore_cache:
          keys:
            - web-nodejs-dependencies-v100-{{ checksum "nodejs-dependency-json-cache.key" }}
  save-nodejs-cache:
    description: "NodeJS: Save cache"
    steps:
      - save_cache:
          key: web-nodejs-dependencies-v100-{{ checksum "nodejs-dependency-json-cache.key" }}
          paths:
            - web/node_modules
            - web/navbar/node_modules
            - web/nodes/node_modules
            - web/root-config/node_modules

jobs:
  build-web:
    executor: web-executor
    steps:
      - checkout
      - restore-nodejs-cache
      - save-nodejs-cache
      - run:
          name: Install dependencies
          command: |
            cd web
            yarn
      - run:
          name: Build applications
          command: |
            cd web
            yarn build
      - persist_to_workspace:
          root: ~/project
          paths: web
  build-container:
    executor: docker-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Docker
          command: |
            cd opennms-container/web
            ./build_container_image.sh
      - store_artifacts:
          path: ~/project/opennms-container/web/images/horizon.oci
          destination: horizon.oci
  deploy-container:
    executor: centos-build-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Load OCI
          command: |
            docker image load -i horizon.oci
      - run:
          name: Tag and publish Docker image to registry
          command: |
            cd opennms-container/horizon
            ./tag.sh
            ./publish.sh
